// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhoUEgBjtkP5-20FuGvtHzn7AfIgyWKoM',
    appId: '1:597285063308:web:8981bdb9993b62029c09a9',
    messagingSenderId: '597285063308',
    projectId: 'meucarrinho-fb',
    authDomain: 'meucarrinho-fb.firebaseapp.com',
    storageBucket: 'meucarrinho-fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxZOC89qlMcx41ItCwOXyDpwkYQbR49yg',
    appId: '1:597285063308:android:116cc688f0438b139c09a9',
    messagingSenderId: '597285063308',
    projectId: 'meucarrinho-fb',
    storageBucket: 'meucarrinho-fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSeR2FWj0i2RyEGOdJYdgJZdMbTj7Sk2o',
    appId: '1:597285063308:ios:277427ba0f56856e9c09a9',
    messagingSenderId: '597285063308',
    projectId: 'meucarrinho-fb',
    storageBucket: 'meucarrinho-fb.firebasestorage.app',
    iosBundleId: 'com.example.meucarrinhoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSeR2FWj0i2RyEGOdJYdgJZdMbTj7Sk2o',
    appId: '1:597285063308:ios:277427ba0f56856e9c09a9',
    messagingSenderId: '597285063308',
    projectId: 'meucarrinho-fb',
    storageBucket: 'meucarrinho-fb.firebasestorage.app',
    iosBundleId: 'com.example.meucarrinhoFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhoUEgBjtkP5-20FuGvtHzn7AfIgyWKoM',
    appId: '1:597285063308:web:25e4b90d4081cd5d9c09a9',
    messagingSenderId: '597285063308',
    projectId: 'meucarrinho-fb',
    authDomain: 'meucarrinho-fb.firebaseapp.com',
    storageBucket: 'meucarrinho-fb.firebasestorage.app',
  );
}
